trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Use Python 3.8'

- script: |
    pip install -r environment/requirements_bikes.txt
  displayName: 'Install dependencies'

- script: |
    python models/linear_regression/train.py data/bikes.csv bikes
    python models/random_forest/train.py data/bikes.csv bikes
    python models/decision_tree/train.py data/bikes.csv bikes
  displayName: 'Train all models'

- script: |
    python ci_cd_utils/evaluate_metrics.py bikes LinearRegression
    python ci_cd_utils/evaluate_metrics.py bikes RandomForest
    python ci_cd_utils/evaluate_metrics.py bikes DecisionTree
  displayName: 'Evaluate model metrics'

- script: |
    python ci_cd_utils/compare_models.py bikes
  displayName: 'Compare models and select best'

- script: |
    python ci_cd_utils/deploy_model.py bikes
  displayName: 'Deploy best model'