trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Use Python 3.8'

- script: |
    pip install -r environment/requirements_house.txt
  displayName: 'Install dependencies'

- script: |
    python models/linear_regression/train.py data/house.csv house
    python models/random_forest/train.py data/house.csv house
    python models/decision_tree/train.py data/house.csv house
  displayName: 'Train all models'

- script: |
    python ci_cd_utils/evaluate_metrics.py house LinearRegression
    python ci_cd_utils/evaluate_metrics.py house RandomForest
    python ci_cd_utils/evaluate_metrics.py house DecisionTree
  displayName: 'Evaluate model metrics'

- script: |
    python ci_cd_utils/compare_models.py house
  displayName: 'Compare models and select best'

- script: |
    python ci_cd_utils/deploy_model.py house
  displayName: 'Deploy best model'